steps:
  # 1. Docker イメージをビルドして Container Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/test-shun-347007gcp-test', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/test-shun-347007/gcp-test']

  # 2. Cloud Run にデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'hello-world',
      '--image', 'gcr.io/test-shun-347007/gcp-test',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/test-shun-347007/hello-world'